export const GET_USER_MENULIST_SUCCESS = 'GET_USER_MENULIST_SUCCESS';
export const GET_USER_MENULIST_PENDING = 'GET_USER_MENULIST_PENDING';
export const GET_USER_MENULIST_FAILED = 'GET_USER_MENULIST_FAILED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_PENDING = 'LOGIN_PENDING';

export const GET_TEACHER_PAGE_SUCCESS = 'GET_TEACHER_PAGE_SUCCESS';
export const GET_TEACHER_PAGE_PENDING = 'GET_TEACHER_PAGE_PENDING';
export const GET_TEACHER_PAGE_FAILED = 'GET_TEACHER_PAGE_FAILED';
export const GET_TEACHER_LIST_SUCCESS = 'GET_TEACHER_LIST_SUCCESS';
export const GET_TEACHER_LIST_PENDING = 'GET_TEACHER_LIST_PENDING';
export const GET_TEACHER_LIST_FAILED = 'GET_TEACHER_LIST_FAILED';

export const GET_STUDENT_PAGE_SUCCESS = 'GET_STUDENT_PAGE_SUCCESS';
export const GET_STUDENT_PAGE_PENDING = 'GET_STUDENT_PAGE_PENDING';
export const GET_STUDENT_PAGE_FAILED = 'GET_STUDENT_PAGE_FAILED';
export const GET_STUDENT_LIST_SUCCESS = 'GET_STUDENT_LIST_SUCCESS';
export const GET_STUDENT_LIST_PENDING = 'GET_STUDENT_LIST_PENDING';
export const GET_STUDENT_LIST_FAILED = 'GET_STUDENT_LIST_FAILED';

export const GET_CLASS_PAGE_SUCCESS = 'GET_CLASS_PAGE_SUCCESS';
export const GET_CLASS_PAGE_PENDING = 'GET_CLASS_PAGE_PENDING';
export const GET_CLASS_PAGE_FAILED = 'GET_CLASS_PAGE_FAILED';
export const GET_CLASS_LIST_SUCCESS = 'GET_CLASS_LIST_SUCCESS';
export const GET_CLASS_LIST_PENDING = 'GET_CLASS_LIST_PENDING';
export const GET_CLASS_LIST_FAILED = 'GET_CLASS_LIST_FAILED';
export const GET_COLLEGE_LIST_SUCCESS = 'GET_COLLEGE_LIST_SUCCESS';
export const GET_COLLEGE_LIST_PENDING = 'GET_COLLEGE_LIST_PENDING';
export const GET_COLLEGE_LIST_FAILED = 'GET_COLLEGE_LIST_FAILED';

export const GET_RECENT_STUDENT_PAGE_SUCCESS = 'GET_RECENT_STUDENT_PAGE_SUCCESS';
export const GET_RECENT_STUDENT_PAGE_PENDING = 'GET_RECENT_STUDENT_PAGE_PENDING';
export const GET_RECENT_STUDENT_PAGE_FAILED = 'GET_RECENT_STUDENT_PAGE_FAILED';
export const GET_RECENT_STUDENT_LIST_SUCCESS = 'GET_RECENT_STUDENT_LIST_SUCCESS';
export const GET_RECENT_STUDENT_LIST_PENDING = 'GET_RECENT_STUDENT_LIST_PENDING';
export const GET_RECENT_STUDENT_LIST_FAILED = 'GET_RECENT_STUDENT_LIST_FAILED';

export const GET_SEARCH_PERSON_SUCCESS = 'GET_SEARCH_PERSON_SUCCESS';
export const GET_SEARCH_PERSON_PENDING = 'GET_SEARCH_PERSON_PENDING';
export const GET_SEARCH_PERSON_FAILED = 'GET_SEARCH_PERSON_FAILED';

export const ADD_LAB_RECORD_SUCCESS = 'ADD_LAB_RECORD_SUCCESS';
export const ADD_LAB_RECORD_FAILED = 'ADD_LAB_RECORD_FAILED';
export const ADD_LAB_RECORD_PENDING = 'ADD_LAB_RECORD_PENDING';

export const GET_PERSONAL_INFO_SUCCESS = 'GET_PERSONAL_INFO_SUCCESS';
export const GET_PERSONAL_INFO_FAILED = 'GET_PERSONAL_INFO_FAILED';
export const GET_PERSONAL_INFO_PENDING = 'GET_PERSONAL_INFO_PENDING';
export const CHANGE_PERSONAL_PASSWORD_SUCCESS = 'CHANGE_PERSONAL_PASSWORD_SUCCESS';
export const CHANGE_PERSONAL_PASSWORD_FAILED = 'CHANGE_PERSONAL_PASSWORD_FAILED';
export const CHANGE_PERSONAL_PASSWORD_PENDING = 'CHANGE_PERSONAL_PASSWORD_PENDING';

export const GET_TEAM_PERMISSION_SUCCESS = 'GET_TEAM_PERMISSION_SUCCESS';
export const GET_TEAM_PERMISSION_FAILED = 'GET_TEAM_PERMISSION_FAILED';
export const GET_TEAM_PERMISSION_PENDING = 'GET_TEAM_PERMISSION_PENDING';

export const GET_MACHINE_PAGE_SUCCESS = 'GET_MACHINE_PAGE_SUCCESS';
export const GET_MACHINE_PAGE_PENDING = 'GET_MACHINE_PAGE_PENDING';
export const GET_MACHINE_PAGE_FAILED = 'GET_MACHINE_PAGE_FAILED';
export const GET_CURRENT_EXP_INFO_SUCCESS = 'GET_CURRENT_EXP_INFO_SUCCESS';
export const GET_CURRENT_EXP_INFO_PENDING = 'GET_CURRENT_EXP_INFO_PENDING';
export const GET_CURRENT_EXP_INFO_FAILED = 'GET_CURRENT_EXP_INFO_FAILED';

export const GET_EXPLORE_PROGRESS_SUCCESS = 'GET_EXPLORE_PROGRESS_SUCCESS';
export const GET_EXPLORE_PROGRESS_PENDING = 'GET_EXPLORE_PROGRESS_PENDING';
export const GET_EXPLORE_PROGRESS_FAILED = 'GET_EXPLORE_PROGRESS_FAILED';
export const GET_MACHINE_DISPLAY_SUCCESS = 'GET_MACHINE_DISPLAY_SUCCESS';
export const GET_MACHINE_DISPLAY_PENDING = 'GET_MACHINE_DISPLAY_PENDING';
export const GET_MACHINE_DISPLAY_FAILED = 'GET_MACHINE_DISPLAY_FAILED';

export const GET_MY_LABRECORD_PAGE_SUCCESS = 'GET_MY_LABRECORD_PAGE_SUCCESS';
export const GET_MY_LABRECORD_PAGE_PENDING = 'GET_MY_LABRECORD_PAGE_PENDING';
export const GET_MY_LABRECORD_PAGE_FAILED = 'GET_MY_LABRECORD_PAGE_FAILED';

export const GET_LABTYPE_LIST_SUCCESS = 'GET_LABTYPE_LIST_SUCCESS';
export const GET_LABTYPE_LIST_PENDING = 'GET_LABTYPE_LIST_PENDING';
export const GET_LABTYPE_LIST_FAILED = 'GET_LABTYPE_LIST_FAILED';

export const GET_EXP_GROUP_SUCCESS = 'GET_EXP_GROUP_SUCCESS';
export const GET_EXP_GROUP_PENDING = 'GET_EXP_GROUP_PENDING';
export const GET_EXP_GROUP_FAILED = 'GET_EXP_GROUP_FAILED';

export const GET_LAB_INFO_SUCCESS = 'GET_LAB_INFO_SUCCESS';
export const GET_LAB_INFO_FAILED = 'GET_LAB_INFO_FAILED';
export const GET_LAB_INFO_PENDING = 'GET_LAB_INFO_PENDING';

export const GET_TEAM_LAB_INFO_SUCCESS = 'GET_TEAM_LAB_INFO_SUCCESS';
export const GET_TEAM_LAB_INFO_FAILED = 'GET_TEAM_LAB_INFO_FAILED';
export const GET_TEAM_LAB_INFO_PENDING = 'GET_TEAM_LAB_INFO_PENDING';

export const GET_TEAM_LAB_DETAIL_INFO_SUCCESS = 'GET_TEAM_LAB_DETAIL_INFO_SUCCESS';
export const GET_TEAM_LAB_DETAIL_INFO_FAILED = 'GET_TEAM_LAB_DETAIL_INFO_FAILED';
export const GET_TEAM_LAB_DETAIL_INFO_PENDING = 'GET_TEAM_LAB_DETAIL_INFO_PENDING';

export const GET_LABRECORD_HISTORY_PAGE_SUCCESS = 'GET_LABRECORD_HISTORY_PAGE_SUCCESS';
export const GET_LABRECORD_HISTORY_PAGE_PENDING = 'GET_LABRECORD_HISTORY_PAGE_PENDING';
export const GET_LABRECORD_HISTORY_PAGE_FAILED = 'GET_LABRECORD_HISTORY_PAGE_FAILED';

export const GET_LABTYPE_HISTORY_LIST_SUCCESS = 'GET_LABTYPE_HISTORY_LIST_SUCCESS';
export const GET_LABTYPE_HISTORY_LIST_PENDING = 'GET_LABTYPE_HISTORY_LIST_PENDING';
export const GET_LABTYPE_HISTORY_LIST_FAILED = 'GET_LABTYPE_HISTORY_LIST_FAILED';

export const GET_COLLEGE_HISTORY_LIST_SUCCESS = 'GET_COLLEGE_HISTORY_LIST_SUCCESS';
export const GET_COLLEGE_HISTORY_LIST_PENDING = 'GET_COLLEGE_HISTORY_LIST_PENDING';
export const GET_COLLEGE_HISTORY_LIST_FAILED = 'GET_COLLEGE_HISTORY_LIST_FAILED';

export const GET_LAB_HISTORY_LIST_SUCCESS = 'GET_LAB_HISTORY_LIST_SUCCESS';
export const GET_LAB_HISTORY_LIST_PENDING = 'GET_LAB_HISTORY_LIST_PENDING';
export const GET_LAB_HISTORY_LIST_FAILED = 'GET_LAB_HISTORY_LIST_FAILED';
export const GET_CLASSES_HISTORY_LIST_SUCCESS = 'GET_CLASSES_HISTORY_LIST_SUCCESS';
export const GET_CLASSES_HISTORY_LIST_PENDING = 'GET_CLASSES_HISTORY_LIST_PENDING';
export const GET_CLASSES_HISTORY_LIST_FAILED = 'GET_CLASSES_HISTORY_LIST_FAILED';

export const GET_EXP_DATA_PAGE_SUCCESS = 'GET_EXP_DATA_PAGE_SUCCESS';
export const GET_EXP_DATA_PAGE_PENDING = 'GET_EXP_DATA_PAGE_PENDING';
export const GET_EXP_DATA_PAGE_FAILED = 'GET_EXP_DATA_PAGE_FAILED';

export const GET_EXP_PAGE_SUCCESS = 'GET_EXP_PAGE_SUCCESS';
export const GET_EXP_PAGE_PENDING = 'GET_EXP_PAGE_PENDING';
export const GET_EXP_PAGE_FAILED = 'GET_EXP_PAGE_FAILED';

export const GET_SYSTEM_LOG_SUCCESS = 'GET_SYSTEM_LOG_PAGE_SUCCESS';
export const GET_SYSTEM_LOG_PENDING = 'GET_SYSTEM_LOG_PAGE_PENDING';
export const GET_SYSTEM_LOG_FAILED = 'GET_SYSTEM_LOG_PAGE_FAILED';
export const GET_SYSTEM_SETTING_SUCCESS = 'GET_SYSTEM_SETTING_SUCCESS';
export const GET_SYSTEM_SETTING_PENDING = 'GET_SYSTEM_SETTING_PENDING';
export const GET_SYSTEM_SETTING_FAILED = 'GET_SYSTEM_SETTING_FAILED';

export const GET_ACCOUNT_LIST_SUCCESS = 'GET_ACCOUNT_LIST_SUCCESS';
export const GET_ACCOUNT_LIST_PENDING = 'GET_ACCOUNT_LIST_PENDING';
export const GET_ACCOUNT_LIST_FAILED = 'GET_ACCOUNT_LIST_FAILED';

export const GET_COMPARED_DATA_SUCCESS = 'GET_COMPARED_DATA_SUCCESS';
export const GET_COMPARED_DATA_PENDING = 'GET_COMPARED_DATA_PENDING';
export const GET_COMPARED_DATA_FAILED = 'GET_COMPARED_DATA_FAILED';

export const GET_LAB_MY_LIST_SUCCESS = 'GET_LAB_MY_LIST_SUCCESS';
export const GET_LAB_MY_LIST_PENDING = 'GET_LAB_MY_LIST_PENDING';
export const GET_LAB_MY_LIST_FAILED = 'GET_LAB_MY_LIST_FAILED';
